const products = [
  ['Pulse Pro Headphones','Audio','₹19,990','https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=900&q=85'],
  ['Orbit X1 Watch','Wearables','₹14,990','https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=900&q=85'],
  ['NovaBook Air','Computers','₹89,990','https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=900&q=85'],
  ['Lens Mini 4K','Cameras','₹39,990','https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&w=900&q=85'],
  ['Arc Mechanical Keys','Accessories','₹8,990','https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=900&q=85'],
  ['Halo Smart Home','Smart Home','₹12,990','https://images.unsplash.com/photo-1558002038-1055907df827?auto=format&fit=crop&w=900&q=85']
];
const pages = {
  '/':['Home','Technology,<br>made human.','The devices you want. The guidance you deserve. Welcome to TechX.'],
  '/shop':['Shop','The future is<br>in your hands.','Explore curated technology built for the way you live.'],
  '/categories':['Categories','Find your<br>next obsession.','A considered collection of the technology that matters.'],
  '/deals':['Deals','Good tech.<br>Better prices.','Limited releases and special savings, picked for you.'],
  '/new-arrivals':['New arrivals','Fresh from<br>the frontier.','The newest technology, before it becomes ordinary.'],
  '/audio':['Audio','Hear every<br>detail.','Sound that makes space for everything else to disappear.'],
  '/computers':['Computers','Work without<br>limits.','Remarkable performance for your biggest ideas.'],
  '/mobiles':['Mobiles','Your world,<br>in hand.','Phones that keep your life beautifully in sync.'],
  '/wearables':['Wearables','Made to<br>move with you.','A better read on every day.'],
  '/cameras':['Cameras','Keep the<br>moment close.','Tools for seeing your world differently.'],
  '/smart-home':['Smart home','Home,<br>reimagined.','Thoughtful technology that works quietly in the background.'],
  '/accessories':['Accessories','The finishing<br>touches.','Small details. Significant upgrades.'],
  '/about':['About us','Curious by<br>design.','We believe great technology should feel clear, useful, and a little magical.'],
  '/contact':['Contact us','Let’s talk<br>technology.','Our product specialists are here seven days a week.'],
  '/faq':['FAQs','Questions,<br>answered.','Everything you want to know about TechX.'],
  '/support':['Support','We’re here<br>to help.','Fast answers and genuine support from people who care.'],
  '/shipping':['Shipping','Delivered,<br>delightfully.','Simple, trackable delivery across India.'],
  '/returns':['Returns','Easy does<br>it.','Try it at home. If it is not right, we will make it right.'],
  '/privacy':['Privacy','Your data,<br>your choice.','A clear, respectful approach to privacy.'],
  '/checkout':['Checkout','Nearly yours.','A few details and your TechX order will be on its way.'],
  '/account':['My account','Everything,<br>in one place.','Manage your details, orders and saved favourites.'],
  '/wishlist':['Wishlist','Saved for<br>later.','A beautiful list of things you are considering.'],
  '/track-order':['Track order','Follow your<br>delivery.','Enter your order number to see where it is.']
};
const route=()=>location.hash.slice(1)||'/';
const state={cart:JSON.parse(localStorage.getItem('tx-cart')||'[]'),seen:new Set([route()]),maxScroll:0,purchased:false};
const visitor=localStorage.getItem('tx-visitor')||crypto.randomUUID(); const returning=!!localStorage.getItem('tx-visitor'); localStorage.setItem('tx-visitor',visitor); const started=Date.now();
function nav(){const user=localStorage.getItem('tx-user');return `<header><a class="brand" href="/">TECH<span>X</span></a><nav><a href="/shop">Shop</a><a href="/new-arrivals">New arrivals</a><a href="/deals">Offers</a><a href="/about">Our story</a></nav><div class="nav-right"><button class="search" aria-label="Search">⌕</button><button class="login" onclick="${user?`go('/account')`:'openLogin()'}">${user?'Account':'Log in'}</button><button class="bag" onclick="go('/checkout')">Bag <b>${state.cart.length}</b></button></div></header>`}
function cards(){return `<section class="products"><div class="section-top"><p class="eyebrow">CURATED FOR YOU</p><h2>Worth a closer look.</h2><a href="/shop">View all products ↗</a></div><div class="grid">${products.map((p,i)=>`<article class="product"><div class="product-art"><img src="${p[3]}" alt="${p[0]}"><span>${i%2?'NEW':'TECHX PICK'}</span></div><p class="category">${p[1]}</p><h3>${p[0]}</h3><p>${p[2]}</p><button onclick="add(${i})">Add to bag +</button></article>`).join('')}</div></section>`}
function content(path){if(path==='/contact')return `<section class="info contact"><div><p class="eyebrow">CONTACT TECHX</p><h2>How can we help?</h2><p>Our team is available 9am–9pm, every day.</p></div><form onsubmit="event.preventDefault();alert('Thank you — we will be in touch soon.')"><input placeholder="Your name" required><input placeholder="Email address" type="email" required><textarea placeholder="Tell us what you need"></textarea><button>Send message ↗</button></form></section>`;if(path==='/faq')return `<section class="info"><p class="eyebrow">THE ESSENTIALS</p><div class="faq">${['When will my order arrive?','Can I return a product?','Are products covered by warranty?','How do I track delivery?','How can I pay?'].map(q=>`<details><summary>${q}<i>+</i></summary><p>Our team makes every step simple. Visit Support or contact a TechX specialist for help.</p></details>`).join('')}</div></section>`;if(path==='/checkout')return `<section class="info checkout"><div><p class="eyebrow">YOUR BAG</p><h2>${state.cart.length?`${state.cart.length} item${state.cart.length>1?'s':''}, excellent choice.`:'Your bag is waiting.'}</h2>${state.cart.map(i=>`<p class="line">${products[i][0]} <strong>${products[i][2]}</strong></p>`).join('')}</div>${state.cart.length?'<button onclick="purchase()">Complete purchase ↗</button>':'<a class="button" href="/shop">Explore products ↗</a>'}</section>`;return `<section class="info"><p class="eyebrow">TECHX ${pages[path][0].toUpperCase()}</p><div class="columns"><h2>Designed around real life.</h2><p>Technology should create possibilities, not complications. TechX brings together thoughtful devices, clear advice, and support that stays with you long after checkout.</p><p>Explore with confidence. Every product is selected for quality, performance, and its power to make everyday moments feel better.</p></div></section>`}
function page(){const path=pages[route()]?route():'/';state.seen.add(path);const d=pages[path];document.title=`TechX — ${d[0]}`;const listing=['/shop','/categories','/deals','/new-arrivals','/audio','/computers','/mobiles','/wearables','/cameras','/smart-home','/accessories'].includes(path);document.querySelector('#app').innerHTML=`${nav()}<main><section class="hero"><div class="orb"></div><p class="eyebrow">${path==='/'?'THE TECHX EDIT':d[0]}</p><h1>${d[1]}</h1><p class="sub">${d[2]}</p>${path==='/'?'<a class="button" href="/shop">Shop the collection ↗</a>':''}<div class="hero-number">01 — 23</div></section>${listing||path==='/'?cards():content(path)}<section class="promise"><p>TECHX STANDARD</p><h2>Better tech begins<br>with better choices.</h2><div><span>01</span> Considered selection <span>02</span> Human support <span>03</span> Made to last</div></section></main><footer><a class="brand" href="/">TECH<span>X</span></a><div><a href="/contact">Contact</a><a href="/support">Support</a><a href="/track-order">Track order</a><a href="/privacy">Privacy</a></div><p>© 2026 TechX. Better everyday.</p></footer><div class="modal" id="login-modal" onclick="if(event.target===this)closeLogin()"><form class="login-card" onsubmit="finishLogin(event)"><button type="button" class="close" onclick="closeLogin()">×</button><p class="eyebrow">WELCOME TO TECHX</p><h2>Sign in, simply.</h2><p>Save favourites and keep your orders close.</p><input id="login-name" placeholder="Your name" required><input placeholder="Email address" type="email" required><button>Continue ↗</button></form></div>`;scrollTo({top:0,behavior:'instant'})}
function go(x){location.hash=x} function add(i){state.cart.push(i);localStorage.setItem('tx-cart',JSON.stringify(state.cart));page()} function purchase(){state.purchased=true;state.cart=[];localStorage.setItem('tx-cart','[]');alert('Order confirmed. Thank you for choosing TechX!');page()} function openLogin(){document.querySelector('#login-modal').classList.add('show')} function closeLogin(){document.querySelector('#login-modal').classList.remove('show')} function finishLogin(e){e.preventDefault();localStorage.setItem('tx-user',document.querySelector('#login-name').value);closeLogin();page()}
document.addEventListener('click',e=>{const a=e.target.closest('a[href^="/"]');if(a){e.preventDefault();go(a.getAttribute('href'))}});addEventListener('hashchange',page);addEventListener('scroll',()=>{const h=document.documentElement.scrollHeight-innerHeight;state.maxScroll=Math.max(state.maxScroll,h?Math.round(scrollY/h*100):100)});addEventListener('pagehide',()=>{const data={timestamp:new Date().toISOString(),sessionId:crypto.randomUUID(),visitorId:visitor,duration:Math.round((Date.now()-started)/1000),pages:state.seen.size,scroll:state.maxScroll,purchased:state.purchased,returning};localStorage.setItem('tx-last-session',JSON.stringify(data));navigator.sendBeacon('/api/analytics',new Blob([JSON.stringify(data)],{type:'application/json'}))});page();
