const products = [
  ['Pulse Pro Headphones','Audio','₹19,990','🎧','Adaptive noise cancellation.'], ['Orbit X1 Watch','Wearables','₹14,990','⌚','Health tracking, designed to move.'], ['NovaBook Air','Computers','₹89,990','💻','Powerful. Featherweight.'], ['Lens Mini 4K','Cameras','₹39,990','📷','Clarity in every frame.'], ['Arc Mechanical Keys','Accessories','₹8,990','⌨️','A keystroke worth hearing.'], ['Halo Smart Home','Smart Home','₹12,990','◉','Your home, in harmony.']
];
const pages = {
  '/': {label:'Home', hero:'Technology,\nmade human.', sub:'The devices you want. The guidance you deserve. Welcome to TechX.', cta:'Shop latest'},
  '/shop': {label:'Shop', hero:'The future is\nin your hands.', sub:'Explore curated technology built for the way you live.'},
  '/categories': {label:'Categories', hero:'Find your\nnext obsession.', sub:'A considered collection of the technology that matters.'},
  '/deals': {label:'Deals', hero:'Good tech.\nBetter prices.', sub:'Limited releases and special savings, picked for you.'},
  '/new-arrivals': {label:'New Arrivals', hero:'Fresh from\nthe frontier.', sub:'The newest technology, before it becomes ordinary.'},
  '/audio': {label:'Audio', hero:'Hear every\ndetail.', sub:'Sound that makes space for everything else to disappear.'},
  '/computers': {label:'Computers', hero:'Work without\nlimits.', sub:'Remarkable performance for your biggest ideas.'},
  '/mobiles': {label:'Mobiles', hero:'Your world,\nin hand.', sub:'Phones that keep your life beautifully in sync.'},
  '/wearables': {label:'Wearables', hero:'Made to\nmove with you.', sub:'A better read on every day.'},
  '/cameras': {label:'Cameras', hero:'Keep the\nmoment close.', sub:'Tools for seeing your world differently.'},
  '/smart-home': {label:'Smart Home', hero:'Home,\nreimagined.', sub:'Thoughtful technology that works quietly in the background.'},
  '/accessories': {label:'Accessories', hero:'The finishing\ntouches.', sub:'Small details. Significant upgrades.'},
  '/about': {label:'About us', hero:'Curious by\ndesign.', sub:'We believe great technology should feel clear, useful, and a little magical.'},
  '/contact': {label:'Contact us', hero:'Let’s talk\ntechnology.', sub:'Our product specialists are here seven days a week.'},
  '/faq': {label:'FAQs', hero:'Questions,\nanswered.', sub:'Everything you want to know about TechX.'},
  '/support': {label:'Support', hero:'We’re here\nto help.', sub:'Fast answers and genuine support from people who care.'},
  '/shipping': {label:'Shipping', hero:'Delivered,\ndelightfully.', sub:'Simple, trackable delivery across India.'},
  '/returns': {label:'Returns', hero:'Easy does\nit.', sub:'Try it at home. If it is not right, we will make it right.'},
  '/privacy': {label:'Privacy', hero:'Your data,\nyour choice.', sub:'A clear, respectful approach to your privacy.'},
  '/checkout': {label:'Checkout', hero:'Nearly yours.', sub:'A few details and your TechX order will be on its way.'}
};
const state = {cart:JSON.parse(localStorage.getItem('tx-cart')||'[]'), pageSet:new Set([location.pathname]), maxScroll:0, purchased:false};
const visitorId = localStorage.getItem('tx-visitor') || crypto.randomUUID(); const returning = !!localStorage.getItem('tx-visitor'); localStorage.setItem('tx-visitor',visitorId);
const sessionId=crypto.randomUUID(), started=Date.now();
function nav(){return `<header><a class="brand" href="/">TECH<span>X</span></a><nav><a href="/shop">Shop</a><a href="/new-arrivals">New arrivals</a><a href="/deals">Offers</a><a href="/about">Our story</a></nav><div class="nav-right"><button class="search" aria-label="Search">⌕</button><button class="bag" onclick="go('/checkout')">Bag <b>${state.cart.length}</b></button><button class="menu" onclick="document.body.classList.toggle('open')">☰</button></div></header>`}
function productCards(){return `<section class="products"><div class="section-top"><p class="eyebrow">CURATED FOR YOU</p><h2>Worth a closer look.</h2><a href="/shop">View all products ↗</a></div><div class="grid">${products.map((p,i)=>`<article class="product"><div class="product-art art${i}">${p[3]}<span>${i%2?'NEW':'TECHX PICK'}</span></div><p class="category">${p[1]}</p><h3>${p[0]}</h3><p>${p[2]}</p><button onclick="add(${i})">Add to bag +</button></article>`).join('')}</div></section>`}
function infoContent(path){ if(path==='/contact')return `<section class="info contact"><div><p class="eyebrow">CONTACT TECHX</p><h2>How can we help?</h2><p>Our team is available 9am–9pm, every day.</p></div><form onsubmit="event.preventDefault();alert('Thank you — we’ll be in touch soon.')"><input placeholder="Your name" required><input placeholder="Email address" type="email" required><textarea placeholder="Tell us what you need"></textarea><button>Send message ↗</button></form></section>`; if(path==='/faq')return `<section class="info"><p class="eyebrow">THE ESSENTIALS</p><div class="faq">${['When will my order arrive?','Can I return a product?','Are products covered by warranty?','How do I track my delivery?','How can I pay?'].map(q=>`<details><summary>${q}<i>+</i></summary><p>Yes. Our team makes every step simple. Find more information in Support, or contact a TechX specialist.</p></details>`).join('')}</div></section>`; if(path==='/checkout')return `<section class="info checkout"><div><p class="eyebrow">YOUR BAG</p><h2>${state.cart.length?`${state.cart.length} item${state.cart.length>1?'s':''}, excellent choice.`:'Your bag is waiting.'}</h2>${state.cart.map(i=>`<p class="line">${products[i][0]} <strong>${products[i][2]}</strong></p>`).join('')}</div>${state.cart.length?`<button onclick="purchase()">Complete purchase ↗</button>`:`<a class="button" href="/shop">Explore products ↗</a>`}</section>`; return `<section class="info"><p class="eyebrow">TECHX ${pages[path].label.toUpperCase()}</p><div class="columns"><h2>Designed around real life.</h2><p>Technology should create possibilities, not complications. TechX brings together the most thoughtful devices, clear advice, and support that stays with you long after checkout.</p><p>Explore with confidence. Every product is selected for quality, performance, and its power to make everyday moments feel better.</p></div></section>`}
function page(){const path=pages[location.pathname]?location.pathname:'/'; state.pageSet.add(path); const d=pages[path]; document.title=`TechX — ${d.label}`; const listing=['/shop','/categories','/deals','/new-arrivals','/audio','/computers','/mobiles','/wearables','/cameras','/smart-home','/accessories'].includes(path); document.querySelector('#app').innerHTML=`${nav()}<main><section class="hero"><div class="orb"></div><p class="eyebrow">${path==='/'?'THE TECHX EDIT':d.label}</p><h1>${d.hero.replace('\n','<br>')}</h1><p class="sub">${d.sub}</p>${path==='/'?'<a class="button" href="/shop">Shop the collection ↗</a>':''}<div class="hero-number">01 — 20</div></section>${listing||path==='/'?productCards():infoContent(path)}<section class="promise"><p>TECHX STANDARD</p><h2>Better tech begins<br>with better choices.</h2><div><span>01</span> Considered selection <span>02</span> Human support <span>03</span> Made to last</div></section></main><footer><a class="brand" href="/">TECH<span>X</span></a><div><a href="/contact">Contact</a><a href="/support">Support</a><a href="/privacy">Privacy</a></div><p>© 2026 TechX. Better everyday.</p></footer>`; window.scrollTo({top:0,behavior:'instant'});}
function go(url){history.pushState({},'',url);page()} function add(i){state.cart.push(i);localStorage.setItem('tx-cart',JSON.stringify(state.cart));page()} function purchase(){state.purchased=true;state.cart=[];localStorage.setItem('tx-cart','[]');alert('Order confirmed. Thank you for choosing TechX!');page()}
document.addEventListener('click',e=>{const a=e.target.closest('a[href^="/"]');if(a){e.preventDefault();go(a.getAttribute('href'))}}); addEventListener('popstate',page); addEventListener('scroll',()=>{const h=document.documentElement.scrollHeight-innerHeight;state.maxScroll=Math.max(state.maxScroll,h?Math.round(scrollY/h*100):100)}); function send(){navigator.sendBeacon('/api/analytics',new Blob([JSON.stringify({timestamp:new Date().toISOString(),sessionId,visitorId,duration:Math.round((Date.now()-started)/1000),pages:state.pageSet.size,scroll:state.maxScroll,purchased:state.purchased,returning})],{type:'application/json'}))} addEventListener('pagehide',send); page();
